name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      # Speed up Rust builds
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: "true"
      CARGO_INCREMENTAL: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: sccache cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Cache Rust build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: |
            . -> target
            src-tauri -> src-tauri/target

      - name: Install trunk
        run: cargo install trunk --locked

      - name: Cache Trunk tools (Linux)
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/cache@v4
        with:
          path: ~/.cache/trunk
          key: trunk-${{ runner.os }}-v1
          restore-keys: |
            trunk-${{ runner.os }}-

      - name: Cache Trunk tools (macOS)
        if: matrix.platform == 'macos-latest'
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/trunk
          key: trunk-${{ runner.os }}-v1
          restore-keys: |
            trunk-${{ runner.os }}-

      - name: Cache Trunk tools (Windows)
        if: matrix.platform == 'windows-latest'
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\trunk
          key: trunk-${{ runner.os }}-v1
          restore-keys: |
            trunk-${{ runner.os }}-

      - name: Cache npm (for tauri-action CLI install)
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-v1
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libgtk-3-dev \
            libsoup-3.0-dev \
            libjavascriptcoregtk-4.1-dev

      - name: Build and Publish with Tauri Action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional code signing (set in repo secrets if available)
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          # Uses version from src-tauri/tauri.conf.json
          tagName: v__VERSION__
          releaseName: "vpn9 v__VERSION__"
          releaseBody: "Automated release built by GitHub Actions."
          releaseDraft: false
          prerelease: false
